# Generated by Django 5.2.5 on 2026-08-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Article category',
                'verbose_name_plural': 'Article categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/', verbose_name='featured image')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='author')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articlecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('fr', 'Français')], max_length=2, verbose_name='language')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('excerpt', models.TextField(blank=True, verbose_name='excerpt')),
                ('meta_title', models.CharField(blank=True, max_length=250, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='articles.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'Article translation',
                'verbose_name_plural': 'Article translations',
            },
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('quote', 'Quote')], max_length=20, verbose_name='block type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/blocks/%Y/%m/', verbose_name='image')),
                ('image_caption', models.CharField(blank=True, max_length=250, verbose_name='image caption')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='articles.articletranslation', verbose_name='translation')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='articletranslation',
            constraint=models.UniqueConstraint(fields=('article', 'language'), name='unique_article_language'),
        ),
    ]
