# Generated by Django 5.2.5 on 2026-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblock',
            name='image_caption',
        ),
        migrations.AddField(
            model_name='articleblock',
            name='callout_style',
            field=models.CharField(blank=True, choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=20, verbose_name='callout style'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='articles/documents/%Y/%m/', verbose_name='document'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='heading_level',
            field=models.CharField(blank=True, choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], max_length=2, verbose_name='heading level'),
        ),
        migrations.AddField(
            model_name='articleblock',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='articleblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('quote', 'Quote'), ('callout', 'Callout'), ('divider', 'Divider'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('embed', 'Embed'), ('button', 'Button')], max_length=20, verbose_name='block type'),
        ),
    ]
