# Generated by Django 5.2.5 on 2026-08-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_articleblock_image_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='featured'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
    ]
