# Generated by Django 5.2.5 on 2026-08-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociationInfo',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='role',
            new_name='role_fr',
        ),
    ]
