# Generated by Django 5.2.5 on 2026-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_associationinfo_delete_statistic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AddField(
            model_name='member',
            name='name_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='member',
            name='role_ar',
            field=models.CharField(blank=True, max_length=150, verbose_name='Role (Arabic)'),
        ),
        migrations.AddField(
            model_name='member',
            name='role_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Role (English)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name (Latin characters)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role_fr',
            field=models.CharField(max_length=150, verbose_name='Role (French)'),
        ),
    ]
