# Generated by Django 5.2.5 on 2026-08-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_member_options_member_name_ar_member_role_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='consent'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='wilaya',
            field=models.CharField(choices=[('not_in_algeria', 'I am not living in Algeria'), ('01', 'Adrar'), ('02', 'Chlef'), ('03', 'Laghouat'), ('04', 'Oum El Bouaghi'), ('05', 'Batna'), ('06', 'Béjaïa'), ('07', 'Biskra'), ('08', 'Béchar'), ('09', 'Blida'), ('10', 'Bouira'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Algiers'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arréridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'Naâma'), ('46', 'Aïn Témouchent'), ('47', 'Ghardaïa'), ('48', 'Relizane'), ('49', 'Timimoun'), ('50', 'Bordj Badji Mokhtar'), ('51', 'Ouled Djellal'), ('52', 'Béni Abbès'), ('53', 'In Salah'), ('54', 'In Guezzam'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', "El M'Ghair"), ('58', 'El Meniaa'), ('59', 'Aflou'), ('60', 'Barika'), ('61', 'Ksar Chellala'), ('62', 'Messaad'), ('63', 'Aïn Oussera'), ('64', 'Bou Saâda'), ('65', 'El Bayadh Sidi Cheikh'), ('66', 'El Kantara'), ('67', 'Bir El Ater'), ('68', 'Ksar El Boukhari'), ('69', 'El Aricha')], default=13, max_length=20, verbose_name='wilaya'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('info', 'Information about HTAP'), ('help', 'Request for assistance / support'), ('donate', 'Make a donation or volunteer'), ('partnership', 'Request for partnership / collaboration'), ('activities', 'Information about activities / events'), ('other', 'Other inquiry')], max_length=200, verbose_name='subject'),
        ),
    ]
