# Generated by Django 5.2.5 on 2026-08-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('activity_type', models.CharField(choices=[('event', 'Event'), ('interview', 'Interview'), ('campaign', 'Campaign'), ('meeting', 'Meeting'), ('conference', 'Conference'), ('other', 'Other')], default='event', max_length=30, verbose_name='activity type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='status')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='activities/%Y/%m/', verbose_name='featured image')),
                ('location', models.CharField(blank=True, max_length=250, verbose_name='location')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/gallery/%Y/%m/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='activities.activity', verbose_name='activity')),
            ],
            options={
                'verbose_name': 'Activity image',
                'verbose_name_plural': 'Activity gallery',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French')], max_length=2, verbose_name='language')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('excerpt', models.TextField(blank=True, verbose_name='excerpt')),
                ('meta_title', models.CharField(blank=True, max_length=250, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='activities.activity', verbose_name='activity')),
            ],
            options={
                'verbose_name': 'Activity translation',
                'verbose_name_plural': 'Activity translations',
            },
        ),
        migrations.CreateModel(
            name='ActivityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('quote', 'Quote')], max_length=20, verbose_name='block type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/blocks/%Y/%m/', verbose_name='image')),
                ('image_caption', models.CharField(blank=True, max_length=250, verbose_name='image caption')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='activities.activitytranslation', verbose_name='translation')),
            ],
            options={
                'verbose_name': 'Content block',
                'verbose_name_plural': 'Content blocks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='activitytranslation',
            constraint=models.UniqueConstraint(fields=('activity', 'language'), name='unique_activity_language'),
        ),
    ]
