# Generated by Django 5.2.5 on 2026-08-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('fr', 'Français')], max_length=2, verbose_name='language'),
        ),
    ]
